title: Jekyll AsciiDoc Action
remote_theme: daviddarnes/alembic
description: A GitHub Action to publish AsciiDoc content as a GitHub Pages site
author: Alain Helaili
email: helaili@github.com
timezone: 'Europe/Paris'
exclude:
  - LICENSE.adoc
  - README.adoc
asciidoctor:
  base_dir: :source
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
plugins:
  - "jekyll-remote-theme"